[common]
path = "/tmp/data-writer"
prefix = "test.t1"
start_fileno = 0
end_fileno = 1
rows = 10000
format = "csv"
folders = 0
use_streaming_mode = true
chunk_size = "16MiB"

[parquet]
row_groups = 1
page_size = "1MiB"
compression = "zstd"

[csv]
base64 = false
separator = ","
endline = "\n"
